### ISSUE TITLE
Provisioned Logscale datasource fails

### ISSUE THREAD

**Issue by van-vliet** [grafana/falconlogscale-datasource#104]
**What happened**:
I'm running Grafana on Kubernetes and use provisioning to setup my dashboards and datasources. I've installed the Falcon Logscale datasource plugin and added the following to my list of provisioned datasources:

```
    - name: FalconLogscale
      type: grafana-falconlogscale-datasource
      jsonData:
        baseUrl: https://cloud.humio.com
      secureJsonData:
        accessToken: <my_token>
```

Grafana provisions the datasource. When I look at the settings, I can't see the baseUrl from my provisioned configuration anywhere.
![image](https://github.com/grafana/falconlogscale-datasource/assets/11989400/8df7d6c1-d552-4e8b-b099-b860a6a1111b)

When I try to use the datasource, I get a "plugin.downstreamError" error:
![image](https://github.com/grafana/falconlogscale-datasource/assets/11989400/6183d14a-7918-4c37-9df0-ba91f2f65060)

**What you expected to happen**:
I expected to be able to search for logs using Falcon Logscale as a datasource. I expected to see the baseUrl on the datasource settings page.

**How to reproduce it (as minimally and precisely as possible)**:

1. Add the following datasource to the provisioned datasource list, then start Grafana: 
    ```
    - name: FalconLogscale
       type: grafana-falconlogscale-datasource
       jsonData:
         baseUrl: https://cloud.humio.com
       secureJsonData:
         accessToken: <your_token>
    ```
2. In the Grafana UI, Go to 'Data sources'
3. Click on the FalconLogscale data source.
4. See that the URL field is empty.
5. In Grafana, Go to "Explore". 
6. Select "FalconLogscale". See the "Query error" in the red box immediately.
7. Enter "test" as the search string and then click on "Run query". See the "Query error" return immediately.

**Screenshots**

**Anything else we need to know?**:
I attempted to add the datasource manually using the UI. I only entered the URL and my Falcon Logscale API key.

After saving, the UI shows the data source URL and indicates the API token is present:
![image](https://github.com/grafana/falconlogscale-datasource/assets/11989400/4190cbc3-2429-4dbe-ad0d-1178da94d628)

Searching using the data source on the explore page works:
![image](https://github.com/grafana/falconlogscale-datasource/assets/11989400/df8f103d-4a9d-4e77-9309-ec9e8142563d)

This leads me to believe that the error is related to fields not being provisioned into the data source correctly.

**Environment**:

- Grafana version: Grafana v10.1.2 (8e428858dd)
- Plugin version: 1.1.0
- OS Grafana is installed on: Docker / Amazon Linux
- User OS & Browser: MacOS Ventura 13.5.2. Firefox 118.0.1
- Others:
