### ISSUE TITLE
Cannot set timeout when using data source provisioning

### ISSUE THREAD

**Issue by jvv-trackunit** [grafana/falconlogscale-datasource#236]
**What happened**:
We have a dashboard that uses the Logscale datasource to power some panels.
Our querys toward Logscale time out after 1 minute. See screenshots:
![image](https://github.com/grafana/falconlogscale-datasource/assets/11989400/1cde29c7-e209-4d74-b2ae-fb996eac5ded)
![image](https://github.com/grafana/falconlogscale-datasource/assets/11989400/b9b65998-c8a5-4fa2-98f1-0e98771a079a)

The queries are heavy, so I want to increase the timeout. 

We use provisioning to setup datasources. The official provisioning documentation mentioned a common timeout setting [here](https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources). The plugin documentation mentions provisioning, but [the example](https://github.com/grafana/falconlogscale-datasource/blob/cfabb2a5e5827de6a21d037e24fb1589f5f5c34b/README.md?plain=1#L57) does not show the exact format for specifying the timeout.

I tried including the timeout in two different places in my datasource provisioning settings. I restarted Grafana between each attempt.

```
    - name: FalconLogscale
      type: grafana-falconlogscale-datasource
      url: https://cloud.humio.com
      uid: "<REDACTED>"
      jsonData:
        authenticateWithToken: true
        defaultRepository: <REDACTED>
        timeout: 300
      secureJsonData:
        accessToken: $__file{/etc/secrets/datasources/logscale-api-key}
```
and 
```
    - name: FalconLogscale
      type: grafana-falconlogscale-datasource
      url: https://cloud.humio.com
      uid: "<REDACTED>"
      timeout: 300
      jsonData:
        authenticateWithToken: true
        defaultRepository: <REDACTED>
      secureJsonData:
        accessToken: $__file{/etc/secrets/datasources/logscale-api-key}
```
After performing the change, I get the same error as before. The stats show a total request time of 1 minute, which makes me believe the configuration I've applied has not changed anything.

**What you expected to happen**:
I expected that the README file for this repo described the possible configuration values and showed an example of how to provision them.

I expected one of the two provisioning configurations I applied to have changed the HTTP timeout used towards Logscale. I expected this to allow my dashboard to load without timeout errors.

**How to reproduce it (as minimally and precisely as possible)**:

1. Provision a Logscale datasource using this plugin and the provisioning configuration
```
    - name: FalconLogscale
      type: grafana-falconlogscale-datasource
      url: https://cloud.humio.com
      uid: "<REDACTED>"
      timeout: 300
      jsonData:
        authenticateWithToken: true
        defaultRepository: <REDACTED>
      secureJsonData:
        accessToken: $__file{/etc/secrets/datasources/logscale-api-key}
```
2. Create a dashboard that uses the Logscale datasource. Use one or more queries that are slow to respond.
3. Load the dashboard and wait 1 minute.
4. Observe that the dashboard fails to retrieve data. Press the little "inspect" button on a panel that failed to load Logscale data.
5. In the "Stats" panel, notice that `Total request time` is `1.00 mins`.

**Screenshots**

**Anything else we need to know?**:
I looked through the code to find references to the correct name and placement of the the timeout property. I came across the [plugin settings struct](https://github.com/grafana/falconlogscale-datasource/blame/cfabb2a5e5827de6a21d037e24fb1589f5f5c34b/pkg/plugin/settings.go#L16), where the timeout property is commented. This makes me wonder whether the plugin uses the value at all.

**Environment**:

- Grafana version: Grafana v10.3.3 (252761264e)
- Plugin version: 1.4.1
- OS Grafana is installed on: We use the Grafana docker image. Not sure which OS that uses.
- User OS & Browser: MacOS Sonoma 14.3.1 - Firefox 122.0.1
- Others:
